"""empty message

Revision ID: d0ad20dd3843
Revises: 
Create Date: 2022-11-12 06:31:40.835507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ad20dd3843'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('map_url', sa.String(length=500), nullable=True),
    sa.Column('img_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('coffee_price', sa.String(length=250), nullable=True),
    sa.Column('user_cafe_favorite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_cafe_favorite'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe')
    op.drop_table('user')
    op.drop_table('blocked_list')
    # ### end Alembic commands ###
